# Used when listing blobs
publicDomain: http://cdn.example.com

databasePath: data/sqlite.db

discovery:
  # find files by querying nostr relays
  nostr:
    enabled: true
    relays:
      - wss://nostrue.com
      - wss://relay.damus.io
      - wss://nostr.wine
      - wss://nos.lol
      - wss://nostr-pub.wellorder.net
  # find files by asking upstream CDNs
  upstream:
    enabled: true
    domains:
      - https://cdn.satellite.earth

storage:
  # local or s3
  backend: local
  local:
    dir: ./data
  # s3:
  #   endpoint: https://s3.endpoint.com
  #   bucket: blossom
  #   accessKey: xxxxxxxx
  #   secretKey: xxxxxxxxx
  #   If this is set the server will redirect clients when loading blobs
  #   publicURL: https://s3.region.example.com/

  # rules are checked in descending order. if a blob matches a rule it is kept
  # "type" (required) the type of the blob, "*" can be used to match any type
  # "expiration" (required) time passed since last accessed
  # "pubkeys" (optional) a list of owners
  # any blobs not matching the rules will be removed
  rules:
    # mime type of blob
    - type: text/*
      # time since last accessed
      expiration: 1 month
    - type: "image/*"
      expiration: 1 week
    - type: "video/*"
      expiration: 5 days
    - type: "model/*"
      expiration: 1 week
    - type: "*"
      expiration: 2 days

upload:
  # enable / disable uploads
  enabled: true
  # require auth to upload
  requireAuth: true
  # only check rules that include "pubkeys"
  requirePubkeyInRule: false

list:
  requireAuth: false
  allowListOthers: true

tor:
  enabled: false
  proxy: ""
